verbose=false
max_width=120
comment_width=120
tab_spaces=2
fn_call_width=120
struct_lit_width=32
fn_call_style="Visual"
single_line_if_else_max_width=120
trailing_comma="Vertical"
chain_indent="Visual"
chain_one_line_max=120
reorder_imports=true
format_strings=false
hard_tabs=false
wrap_match_arms=false
error_on_line_overflow=false